version: '3.8'

services:
  phoenix:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: misli_api_dev
      PGHOST: db
      PGPORT: 5432
    depends_on:
      - db
    command:
      - "./entrypoint.sh"
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./_pgdata:/var/lib/postgresql/data